### ISSUE TITLE
Is it possible to merge the fix of node-red-contrib-wstt-stream-fixed in this node ?

### ISSUE THREAD

**Issue by janvda** [ullumullu/node-red-contrib-wstt-stream#1]
Hi,

I think this is a really interesting node.
I noticed there is another node "node-red-contrib-wstt-stream-fixed" that is a fixed version of this node.  Would it be possible to integrate the fix in this node ?

kr
Jan.

**Comment by ullumullu** [comment]
Hi Jan,

This fix should already be part of the repo. I'm busy during the week but will check out both your issues during the weekend. (Both of them are valid and good points ;) )

Cheers,
Sven
